print("I got a dog.")
print("He died.")
print("I buried him in the backyard.")
print("He rose from the dead.")
print("Now he's haunting me for food.")
print("I ate him instead.")
print("He was surprisingly delicious.")
print("I shared him with my family.")
print("They dont know,but loved it I should make dog more often.")
print("Actually I might try cat next.")
print()
